### ISSUE TITLE
allow user-specified tl-indices for crossings (trac #2822)

### ISSUE THREAD

**Issue by behrisch** [DLR-TS/sumo#2822] opened 2017-01-27 10:27 UTC
Migrated from http://sumo.dlr.de/ticket/2822
```json
{
    "status": "new", 
    "changetime": "2017-01-27T10:27:11Z", 
    "description": "", 
    "reporter": "namdre", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1485512831493598", 
    "component": "net building (NETGEN, NETCONVERT)", 
    "summary": "allow user-specified tl-indices for crossings", 
    "priority": "minor", 
    "keywords": "", 
    "time": "2017-01-27T10:27:11Z", 
    "milestone": "1.0.0", 
    "owner": "", 
    "type": "enhancement"
}
```

**Comment by namdre** [comment] 2018-02-15 08:09
duplicate of #2545

**Closed by namdre** 2018-02-15 08:09 UTC
Labels: a:NETCONVERT, a:NETGENERATE, enhancement, p:minor
